services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    restart: unless-stopped
    ports:
      - "30001:8080"
    networks:
      - devops_net

networks:
  devops_net:
    name: devops_net
    external: true