spring.application.name=api-core
server.port=8081

# Configurações de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-rough-water-ac48fzvg-pooler.sa-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hI9RpqGP6VcF

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Banco de dados
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect

# Outras configurações 
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.platform=postgresql

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.open-in-view=false

# COGNITO

aws.cognito.region=sa-east-1
aws.cognito.url=https://cognito-idp.sa-east-1.amazonaws.com

aws.cognito.userPoolId=sa-east-1_PFVOwBpzb

aws.cognito.clientId=1h6kq05sgrb01mfh3tt7mlqapm
aws.cognito.clientSecret=1jo32icak5rlgr2782aunnromdcvm08gdkq9dkoti2r5b6v34b3m